#!/usr/bin/env python3
"""Transcribe the supplementary-experiment ledgers (docs/SUPPLEMENTARY_E*_20260921.json,
docs/G0_INTEGRITY_STATUS_20260921.json) into

  thesis/latex/config/numbers_supp.tex      -- macros used in prose
  thesis/latex/tables/gen/tab_*.tex         -- generated tables (numbers inline)
  thesis/docs/NUMBERS_SUPP.md               -- macro registry: statistic / numerator /
                                               denominator / condition / weighting / source

Pure transcription with fixed rounding: no value is computed from other values.
Rounding: Brier 4 dp; ΔBrier and CI 5 dp (signed); rates 3 dp; seconds 1 dp; counts with {,}.
`check_numbers_supp.py` regenerates into a temp dir and diffs, so a drift between the JSON
ledgers and the LaTeX sources fails the build gate.
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
DOCS = ROOT / "docs"

FILES = {
    "E1": "SUPPLEMENTARY_E1_INFOGROUPS_20260921.json",
    "E2S": "SUPPLEMENTARY_E2_FRAME_STRATA_20260921.json",
    "E2H": "SUPPLEMENTARY_E2_S_HOLD_20260921.json",
    "E3": "SUPPLEMENTARY_E3_EXT_BOOTSTRAP_20260921.json",
    "E4": "SUPPLEMENTARY_E4_SENSITIVITY_20260921.json",
    "E4F": "SUPPLEMENTARY_E4_E_FIXED_20260921.json",
    "OAT": "SUPPLEMENTARY_E4_DEFINITION_OAT_20260921.json",
    "E5": "SUPPLEMENTARY_E5_CORRESPONDENCE_20260921.json",
    "E5M": "SUPPLEMENTARY_E5_MARKET_R0R1_20260921.json",
    "G0": "G0_INTEGRITY_STATUS_20260921.json",
}


def load(key):
    return json.load(open(DOCS / FILES[key], encoding="utf-8"))


# ---------------------------------------------------------------- formatting
def sgn5(x):
    return f"{x:+.5f}"


def f5(x):
    return f"{x:.5f}"


def f4(x):
    return f"{x:.4f}"


def f3(x):
    return f"{x:.3f}"


def f1(x):
    return f"{x:.1f}"


def f8(x):
    return f"{x:.8f}"


def pct1(x):
    return f"{100 * x:.1f}"


def fint(n):
    return f"{int(n):,}".replace(",", "{,}")


def ci5(pair):
    lo, hi = pair
    return f"[{lo:+.5f}, {hi:+.5f}]"


def tex(s):
    return str(s).replace("_", r"\_").replace("%", r"\%")


# ---------------------------------------------------------------- registry
class Registry:
    def __init__(self):
        self.rows = []  # (macro, value, stat, num, den, cond, weight, source)
        self.names = set()

    def add(self, macro, value, stat, num="—", den="—", cond="—", weight="—", source="—"):
        if macro in self.names:
            raise SystemExit(f"duplicate macro {macro}")
        self.names.add(macro)
        self.rows.append((macro, value, stat, num, den, cond, weight, source))

    def tex(self):
        out = [
            "%% GENERATED by thesis/tools/gen_supp.py from docs/SUPPLEMENTARY_*_20260921.json and",
            "%% docs/G0_INTEGRITY_STATUS_20260921.json. Do not edit by hand; run the generator.",
            "%% Registry with statistic / numerator / denominator / source: thesis/docs/NUMBERS_SUPP.md",
            "",
        ]
        for m, v, *_ in self.rows:
            out.append(f"\\newcommand{{\\{m}}}{{{v}}}")
        return "\n".join(out) + "\n"

    def md(self, tables):
        out = [
            "# 보완 실험 수치 레지스트리 (NUMBERS_SUPP)",
            "",
            "`latex/config/numbers_supp.tex`와 `latex/tables/gen/*.tex`는 `tools/gen_supp.py`가 아래 출처에서 **생성**한다.",
            "손으로 고치지 않는다. `tools/check_numbers_supp.py`가 재생성해 차이가 있으면 실패한다.",
            "모든 값은 보완 실험(15.16 노출 이후의 진단, `docs/SUPPLEMENTARY_EXPERIMENT_DESIGN_20260921.md`)이며 헤드라인을 대체하지 않는다.",
            "반올림: Brier 4자리, ΔBrier·구간 5자리(부호 포함), 비율 3자리, 초 1자리.",
            "",
            "## 생성 표",
            "",
            "| 파일 | 내용 | 출처 |",
            "|---|---|---|",
        ]
        for fn, desc, src in tables:
            out.append(f"| `latex/tables/gen/{fn}` | {desc} | {src} |")
        out += [
            "",
            "## 매크로",
            "",
            "| 매크로 | 값 | 통계량 | 분자 | 분모 | 조건 | 가중 | 출처 파일 → 필드 |",
            "|---|---|---|---|---|---|---|---|",
        ]
        for m, v, stat, num, den, cond, wt, src in self.rows:
            out.append(f"| `\\{m}` | {v} | {stat} | {num} | {den} | {cond} | {wt} | {src} |")
        return "\n".join(out) + "\n"


R = Registry()
TABLES = {}  # filename -> tex
TABLE_DESC = []

MW = "경기 가중 (1/n_m)"


def table(fn, desc, src, body):
    TABLES[fn] = body
    TABLE_DESC.append((fn, desc, src))


def wrap_table(caption, label, colspec, header, rows, note, size=r"\small", extra_pre=""):
    lines = [
        "%% GENERATED by thesis/tools/gen_supp.py -- do not edit",
        r"\begin{table}[!t]",
        r"  \centering",
        f"  \\caption{{{caption}}}",
        f"  \\label{{{label}}}",
        f"  {size}",
        extra_pre,
        f"  \\begin{{tabular}}{{{colspec}}}",
        r"    \toprule",
        "    " + header + r" \\",
        r"    \midrule",
    ]
    lines += ["    " + r + r" \\" for r in rows]
    lines += [r"    \bottomrule", r"  \end{tabular}", f"  \\tabnote{{{note}}}", r"\end{table}", ""]
    return "\n".join(l for l in lines if l is not None)


# =============================================================== E1 info groups
def gen_e1():
    e1 = load("E1")
    src = "`SUPPLEMENTARY_E1_INFOGROUPS_20260921.json`"
    armlabel = {"M-F0": "C+Q0", "M-F1": "C+Q0+F", "M-F2": "C+Q0+E", "M-F3": "C+Q0+F+E"}
    armkey = {"M-F0": "Fzero", "M-F1": "Fone", "M-F2": "Ftwo", "M-F3": "Fthree"}
    arm_rows = []
    for c in ("T", "S"):
        coh = e1["cohorts"][c]
        for arm in ("M-F0", "M-F1", "M-F2", "M-F3"):
            sel = coh["selected"][arm]
            b = coh["arm_brier"][arm]
            R.add(f"ig{c}Brier{armkey[arm]}", f4(b), f"{arm} TEST Brier ({c})", "Σ w·(p−y)²", f"{c} 15.16 TEST 행",
                  "항등 보정기; 후보는 Q_SELECT 경기 가중 Brier 최저", MW, f"{src} `cohorts.{c}.arm_brier.{arm}`")
            if c == "T":
                R.add(f"igDim{armkey[arm]}", str(sel["n_features"]), f"{arm} 입력 차원", source=f"{src} `cohorts.T.selected.{arm}.n_features`")
            arm_rows.append(
                f"{c} & {arm} ({armlabel[arm]}) & {sel['n_features']} & {tex(sel['cand_id'])} ({sel['best_iteration']}) & {f4(b)}"
            )
        for key, name, mac in (
            ("D_E_given_F", r"$D_{E\mid F}$ = M-F3 $-$ M-F1", "DEgF"),
            ("D_F_given_E", r"$D_{F\mid E}$ = M-F3 $-$ M-F2", "DFgE"),
            ("M-F1_minus_M-F0", "M-F1 $-$ M-F0", "FoneVsFzero"),
            ("M-F2_minus_M-F0", "M-F2 $-$ M-F0", "FtwoVsFzero"),
            ("M-F3_minus_M-F0", "M-F3 $-$ M-F0", "FthreeVsFzero"),
        ):
            ct = coh["contrasts"][key]
            d = ct["delta_match_mean"]
            lo, hi = ct["ci95"]
            R.add(f"ig{c}{mac}", sgn5(d), f"ΔBrier {key} ({c})", "mean_m[mean_i(Brier_a − Brier_b)]", f"{fint(ct['n_matches'])} 경기 / {fint(ct['n_rows'])} 행",
                  "음수 = 앞 arm이 낮음", "경기 평균", f"{src} `cohorts.{c}.contrasts.{key}.delta_match_mean`")
            R.add(f"ig{c}{mac}Lo", sgn5(lo), "95% 구간 하한", cond="경기 군집 백분위 부트스트랩", source=f"{src} `...{key}.ci95[0]`")
            R.add(f"ig{c}{mac}Hi", sgn5(hi), "95% 구간 상한", cond="경기 군집 백분위 부트스트랩", source=f"{src} `...{key}.ci95[1]`")
    # contrasts table rows
    con_rows = []
    for c in ("T", "S"):
        coh = e1["cohorts"][c]
        for key, name in (
            ("D_E_given_F", r"$D_{E\mid F}$: M-F3 $-$ M-F1 (사건 추가)"),
            ("D_F_given_E", r"$D_{F\mid E}$: M-F3 $-$ M-F2 (프레임 추가)"),
            ("M-F1_minus_M-F0", "M-F1 $-$ M-F0"),
            ("M-F2_minus_M-F0", "M-F2 $-$ M-F0"),
            ("M-F3_minus_M-F0", "M-F3 $-$ M-F0"),
        ):
            ct = coh["contrasts"][key]
            con_rows.append(f"{c} & {name} & {sgn5(ct['delta_match_mean'])} & {ci5(ct['ci95'])}")
    table(
        "tab_infogroups_arms.tex",
        "E1 정보군 arm별 TEST Brier (T, S)",
        f"{src} `cohorts.*.arm_brier`, `selected`",
        wrap_table(
            "정보군 arm의 입력과 Brier 점수 (15.16 TEST)", "tab:infogroups-arms",
            "@{}llrlr@{}", "코호트 & arm (입력) & 차원 & 선택 후보 (반복) & Brier", arm_rows,
            "Brier: 경기 가중, 항등 보정기, 소수 넷째 자리. 후보는 15.15 Q\\_SELECT의 경기 가중 Brier 최저(LightGBM \\texttt{num\\_leaves}$\\times$\\texttt{min\\_child\\_samples} 4개). "
            "C = $p_{\\mathrm{pre}}$, 경기 시각, 경기 시각$^2$; Q0 = 미확인 오브젝트 팀 수; F = 프레임 특징 90열; E = 사건 특징 258열.",
        ),
    )
    table(
        "tab_infogroups_contrasts.tex",
        "E1 정보군 대비 ΔBrier와 95% 구간 (T, S)",
        f"{src} `cohorts.*.contrasts`",
        wrap_table(
            "정보군 대비의 ΔBrier와 구간 (15.16 TEST)", "tab:infogroups-contrasts",
            "@{}llrl@{}", r"코호트 & 대비 & $\Delta$Brier & 95\% 구간", con_rows,
            "$\\Delta$Brier = 경기 평균 차이(앞 arm $-$ 뒤 arm), 음수이면 앞 arm이 낮음; 구간 = 95\\% 경기 군집 백분위 부트스트랩. "
            "T 24{,}020 경기 / 32{,}981 행, S 49{,}730 경기 / 101{,}205 행. 주 대비는 $D_{E\\mid F}$와 $D_{F\\mid E}$(코호트별 두 개, 합 넷).",
        ),
    )


# =============================================================== E2 frame strata + S_hold
def gen_e2():
    e2 = load("E2S")["section_5_4"]
    src = "`SUPPLEMENTARY_E2_FRAME_STRATA_20260921.json`"
    cellname = {
        "same_young": "같은 프레임, 나이 $<$30 s",
        "same_old": "같은 프레임, 나이 $\\ge$30 s",
        "new_young": "새 프레임, 나이 $<$30 s",
        "new_old": "새 프레임, 나이 $\\ge$30 s",
        "all": "전체",
    }
    code = {"same_young": "sy", "same_old": "so", "new_young": "ny", "new_old": "no", "all": "all"}
    rows = []
    for c in ("T", "S"):
        coh = e2[c]
        R.add(f"fs{c}SameFrame", pct1(coh["same_frame_rate"]), "같은 프레임 비율 (%)", "예측·결과 시점이 같은 분 프레임을 읽은 행", f"{c} TEST 행", source=f"{src} `section_5_4.{c}.same_frame_rate`")
        R.add(f"fs{c}PreAgeLt", pct1(coh["pre_age_lt30_rate"]), "예측 시점 프레임 나이 <30 s 비율 (%)", "pre_frame_age < 30 s", f"{c} TEST 행", source=f"{src} `...pre_age_lt30_rate`")
        R.add(f"fs{c}PreAgeMed", f1(coh["pre_age_median_s"]), "예측 시점 프레임 나이 중앙값 (s)", source=f"{src} `...pre_age_median_s`")
        R.add(f"fs{c}FollowMed", f1(coh["followup_median_s"]), "실제 추적 길이 중앙값 (s)", source=f"{src} `...followup_median_s`")
        for cell in ("same_young", "same_old", "new_young", "new_old", "all"):
            d = coh["cells"][cell]
            k = code[cell]
            R.add(f"fs{c}{k}N", fint(d["n"]), f"셀 행 수 ({c}, {cell})", source=f"{src} `...cells.{cell}.n`")
            R.add(f"fs{c}{k}M", fint(d["n_matches"]), f"셀 경기 수 ({c}, {cell})", source=f"{src} `...cells.{cell}.n_matches`")
            R.add(f"fs{c}{k}Psvi", f3(d["P_SVI"]), "SVI 양성률", "Y=1 행", "셀 행", weight=MW, source=f"{src} `...cells.{cell}.P_SVI`")
            R.add(f"fs{c}{k}Edv", f3(d["E_abs_dV"]), "E|ΔV|", weight=MW, source=f"{src} `...cells.{cell}.E_abs_dV`")
            R.add(f"fs{c}{k}Db", sgn5(d["delta_brier_q_minus_pt"]), "ΔBrier q − PT_flex", "Brier(q) − Brier(PT_flex)", "셀 행", "동결 점수; 셀 안에서 가중 재계산", MW, f"{src} `...cells.{cell}.delta_brier_q_minus_pt`")
            rows.append(
                f"{c} & {cellname[cell]} & {fint(d['n'])} & {fint(d['n_matches'])} & {f3(d['P_SVI'])} & {f3(d['E_abs_dV'])} & {sgn5(d['delta_brier_q_minus_pt'])} & {f3(d['mean_p_pre'])} & {f1(d['mean_tmin'])}"
            )
    table(
        "tab_frame_strata.tex",
        "E2 관측 갱신 2×2 층화 (T, S)",
        f"{src} `section_5_4.*.cells`",
        wrap_table(
            "관측 갱신 층화별 결과 (15.16 TEST)", "tab:frame-strata",
            "@{}llrrrrrrr@{}",
            r"코호트 & 셀 & $n$ & 경기 & $P(\mathrm{SVI}{=}1)$ & $\mathbb{E}|\Delta\hat V|$ & $\Delta$Brier & $\bar p_{\mathrm{pre}}$ & $\bar t$ (분)",
            rows,
            "셀 = 예측 시점과 결과 시점 사이에 새 분 프레임이 들어왔는지(같은/새 프레임) $\\times$ 예측 시점 프레임의 나이(30 s 기준). "
            "$\\Delta$Brier = $q - \\mathrm{PT}_{\\mathrm{flex}}$, 동결 점수, 셀 안에서 경기 가중 재계산, 구간 없음. 조성의 진단이며 인과 효과가 아니다.",
            size=r"\footnotesize",
        ),
    )
    # S_hold
    sh = load("E2H")["full"]
    srch = "`SUPPLEMENTARY_E2_S_HOLD_20260921.json` `full`"
    R.add("shN", fint(sh["n_ok"]), "S_hold 재구성 성공 행 (T TEST)", source=f"{srch}.n_ok")
    R.add("shIdentity", f3(sh["arith_identity_rate"]), "ΔV = d_clock + d_update 성립 비율", "|ΔV − (d_clock + d_update)| ≤ 1e−6", "성공 행", source=f"{srch}.arith_identity_rate")
    for q, nm, ko in (("delta_V", "Dv", "ΔV̂"), ("d_clock", "Clock", "d_clock"), ("d_update", "Upd", "d_update")):
        R.add(f"sh{nm}Mean", sgn5(sh[q]["mean"]), f"{ko} 평균", weight="비가중", source=f"{srch}.{q}.mean")
        R.add(f"sh{nm}Abs", f4(sh[q]["mean_abs"]), f"{ko} 평균 절댓값", weight="비가중", source=f"{srch}.{q}.mean_abs")
        R.add(f"sh{nm}Pos", f3(sh[q]["p_pos"]), f"{ko} > 0 비율", f"{ko} > 0 행", "성공 행", "정확한 0 없음 (p_zero = 0)", "비가중", f"{srch}.{q}.p_pos")
    R.add("shFlip", f3(sh["Y_vs_d_update_pos_flip"]), "Y_SVI ≠ 1[d_update > 0] 비율", "불일치 행", "성공 행", weight="비가중", source=f"{srch}.Y_vs_d_update_pos_flip")
    R.add("shOpp", f3(sh["opposite_sign_clock_update_rate"]), "sign(d_clock) ≠ sign(d_update) 비율", "부호가 다른 행", "성공 행", "정확한 0 없음", "비가중", f"{srch}.opposite_sign_clock_update_rate")
    R.add("shHoldAge", f1(sh["mean_hold_snapshot_age_s"]), "hold 상태의 스냅샷 나이 평균 (s)", source=f"{srch}.mean_hold_snapshot_age_s")
    R.add("shFollow", f1(sh["mean_followup_s"]), "결과 시점까지의 평균 추적 길이 (s)", source=f"{srch}.mean_followup_s")
    R.add("shSubN", fint(load("E2H")["subsample"]["n_ok"]), "예비 부표본 행 수", source="`SUPPLEMENTARY_E2_S_HOLD_20260921.json` `subsample.n_ok`")
    rows = []
    for q, ko in (("delta_V", r"$\Delta\hat V = P - A$"), ("d_clock", r"$d_{\mathrm{clock}} = H - A$"), ("d_update", r"$d_{\mathrm{update}} = P - H$")):
        rows.append(f"{ko} & {sgn5(sh[q]['mean'])} & {f4(sh[q]['mean_abs'])} & {f3(sh[q]['p_pos'])}")
    table(
        "tab_shold.tex",
        "E2 S_hold 산술 분해 (T)",
        srch,
        wrap_table(
            "시간 경과와 관측 갱신의 산술 분해 (T, 15.16 TEST)", "tab:shold",
            "@{}lrrr@{}", r"성분 & 평균 & 평균 절댓값 & 양수 비율", rows,
            f"$A = \\hat V(S_{{\\mathrm{{pre}}}})$, $H = \\hat V(S_{{\\mathrm{{hold}}}})$, $P = \\hat V(S_{{\\mathrm{{post}}}})$; $S_{{\\mathrm{{hold}}}}$는 예측 시점까지의 프레임·사건만 유지한 채 질의 시각을 결과 시점으로 옮긴 상태. "
            f"$n = {fint(sh['n_ok'])}$, 항등 성립 {f3(sh['arith_identity_rate'])}, 비가중, 정확한 0 없음. hold 스냅샷 나이 평균 {f1(sh['mean_hold_snapshot_age_s'])} s.",
        ),
    )


# =============================================================== E3 external bootstrap
def gen_e3():
    e3 = load("E3")
    src = "`SUPPLEMENTARY_E3_EXT_BOOTSTRAP_20260921.json`"
    R.add("ebBoot", fint(e3["n_boot"]), "부트스트랩 반복 수", source=f"{src} `n_boot`")
    R.add("ebSeed", str(e3["seed"]), "시드", source=f"{src} `seed`")
    rows = []
    setname = {"KR_16.13": "KR 16.13", "NA1_16.13": "NA1 16.13"}
    setkey = {"KR_16.13": "KR", "NA1_16.13": "NA"}
    for c in ("T", "S"):
        for s in ("KR_16.13", "NA1_16.13"):
            cell = e3["primary"][f"{c}|{s}"]
            assert cell["ok"], f"E3 cell {c}|{s} not ok"
            b = cell["bootstrap"]
            p = f"eb{c}{setkey[s]}"
            base = f"{src} `primary.{c}|{s}`"
            R.add(f"{p}n", fint(cell["n_rows"]), f"행 수 ({c}, {s})", source=f"{base}.n_rows")
            R.add(f"{p}m", fint(cell["n_matches"]), f"경기 수 ({c}, {s})", source=f"{base}.n_matches")
            R.add(f"{p}Bq", f4(cell["brier_q"]), "Brier q (동결)", weight=MW, source=f"{base}.brier_q")
            R.add(f"{p}Bpt", f4(cell["brier_pt"]), "Brier PT_flex (동결)", weight=MW, source=f"{base}.brier_pt")
            R.add(f"{p}D", sgn5(b["estimate"]), "ΔBrier q − PT_flex", "mean_m d_m, d_m = mean_i[(q−y)² − (PT−y)²]", f"{fint(cell['n_matches'])} 경기", "동결 모델, 재학습 없음", "경기 평균", f"{base}.bootstrap.estimate")
            R.add(f"{p}Lo", sgn5(b["ci95"][0]), "95% 구간 하한", cond="경기 군집 백분위, 10,000회", source=f"{base}.bootstrap.ci95[0]")
            R.add(f"{p}Hi", sgn5(b["ci95"][1]), "95% 구간 상한", cond="경기 군집 백분위, 10,000회", source=f"{base}.bootstrap.ci95[1]")
            R.add(f"{p}LoB", sgn5(b["ci9875"][0]), "98.75% 구간 하한", cond="Bonferroni 0.05/4", source=f"{base}.bootstrap.ci9875[0]")
            R.add(f"{p}HiB", sgn5(b["ci9875"][1]), "98.75% 구간 상한", cond="Bonferroni 0.05/4", source=f"{base}.bootstrap.ci9875[1]")
            R.add(f"{p}Frac", f3(b["frac_boot_gt0"]), "부트스트랩 추출 중 Δ>0 비율 (p값 아님)", source=f"{base}.bootstrap.frac_boot_gt0")
            rows.append(
                f"{c} & {setname[s]} & {fint(cell['n_rows'])} & {fint(cell['n_matches'])} & {f4(cell['brier_q'])} & {f4(cell['brier_pt'])} & {sgn5(b['estimate'])} & {ci5(b['ci95'])} & {ci5(b['ci9875'])}"
            )
    hrows = []
    for s in ("KR_16.13", "NA1_16.13"):
        h = e3["common_match_H"][s]
        p = f"ebH{setkey[s]}"
        base = f"{src} `common_match_H.{s}`"
        keys = list(h.keys())
        n_common = h.get("n_common", h.get("n_matches"))
        est = h.get("H", h.get("estimate"))
        ci = h.get("ci95")
        R.add(f"{p}n", fint(n_common), f"공통 경기 수 ({s})", "T와 S 행을 모두 가진 경기", source=f"{base}.n_common")
        R.add(f"{p}", sgn5(est), "H = mean_m(d_mT − d_mS)", "경기별 T 손실차 − S 손실차", f"{fint(n_common)} 공통 경기", "전체 코호트 D_T − D_S와 다른 대상", "경기 평균", f"{base}.H")
        R.add(f"{p}Lo", sgn5(ci[0]), "H 95% 구간 하한", source=f"{base}.ci95[0]")
        R.add(f"{p}Hi", sgn5(ci[1]), "H 95% 구간 상한", source=f"{base}.ci95[1]")
        hrows.append(f"{setname[s]} & {fint(n_common)} & {sgn5(est)} & {ci5(ci)}")
    table(
        "tab_ext_bootstrap.tex",
        "E3 외부 표본의 짝 경기 군집 부트스트랩 (T/S × KR/NA1)",
        f"{src} `primary`",
        wrap_table(
            "외부 표본의 짝 경기 군집 부트스트랩 (16.13)", "tab:ext-bootstrap",
            "@{}llrrrrrll@{}",
            r"코호트 & 표본 & $n$ & 경기 & Brier $q$ & Brier PT & $\Delta$Brier & 95\% 구간 & 98.75\% 구간",
            rows,
            f"동결 $\\hat V$, $q$, $\\mathrm{{PT}}_{{\\mathrm{{flex}}}}$(S는 $q_S$, $\\mathrm{{PT}}_{{\\mathrm{{flex}}}}^S$)의 점수; 재학습·재보정 없음. Brier는 경기 가중, $\\Delta$Brier는 경기 평균 차이($q - \\mathrm{{PT}}$, 음수이면 $q$ 우세). "
            f"구간은 {fint(e3['n_boot'])}회 경기 군집 백분위 부트스트랩(시드 {e3['seed']}); 98.75\\%는 네 대비 Bonferroni. 구간은 고정된 모델에 조건부이며 모델 적합 불확실성을 포함하지 않는다.",
            size=r"\footnotesize",
        ),
    )
    table(
        "tab_ext_common_h.tex",
        "E3 공통 경기 대비 H (KR, NA1)",
        f"{src} `common_match_H`",
        wrap_table(
            "공통 경기에서의 T$-$S 손실차 대비 (16.13)", "tab:ext-common-h",
            "@{}lrrl@{}", r"표본 & 공통 경기 & $H$ & 95\% 구간", hrows,
            "$H = \\mathrm{mean}_m(d_{mT} - d_{mS})$, $d_{mc}$ = 경기 $m$·코호트 $c$의 행 평균 $[(q-y)^2 - (\\mathrm{PT}-y)^2]$; T와 S 행을 모두 가진 경기만. 전체 코호트의 $D_T - D_S$와 다른 대상이며 기전 진술의 근거가 아니다.",
        ),
    )


# =============================================================== E4 horizon / peer / e_fixed / OAT
SCOPE_KO = {
    "all": "전체", "B40": r"$B_{40}$", "small_abs_dV": r"$|\Delta\hat V|<0.05$", "same_frame": "같은 프레임",
    "new_frame": "새 프레임", "t_2_10": r"$t\in[2,10)$", "t_10_20": r"$t\in[10,20)$", "t_20_30": r"$t\in[20,30)$", "t_30_inf": r"$t\ge30$",
}
SCOPE_MAC = {"all": "All", "B40": "Bforty", "small_abs_dV": "Small", "same_frame": "SameF", "new_frame": "NewF",
             "t_2_10": "TtwoTen", "t_10_20": "TtenTwenty", "t_20_30": "TtwentyThirty", "t_30_inf": "TthirtyInf"}


def gen_e4():
    e4 = load("E4")
    src = "`SUPPLEMENTARY_E4_SENSITIVITY_20260921.json`"
    for c in ("T", "S"):
        H = e4["horizon"][c]
        rows = []
        for sc in SCOPE_KO:
            st = H["strata"][sc]
            tr = H["frozen_pred_label_transfer"][sc]["Y_h60"]
            p = f"hz{c}{SCOPE_MAC[sc]}"
            base = f"{src} `horizon.{c}.strata.{sc}`"
            f6090 = st["pairwise_svi"]["h60_vs_h90"]["svi_flip_rate"]
            f90120 = st["pairwise_svi"]["h90_vs_h120"]["svi_flip_rate"]
            same = st["endpoint_identity"]["h60_vs_h90"]["share_same_endpoint"]
            fsame = st["endpoint_identity"]["h60_vs_h90"]["among_same_endpoint_svi_flip"]
            fdiff = st["endpoint_identity"]["h60_vs_h90"]["among_diff_endpoint_svi_flip"]
            R.add(f"{p}N", fint(st["n"]), f"범위 행 수 ({c}, {sc})", source=f"{base}.n")
            R.add(f"{p}FlipSixty", f3(f6090), "SVI 뒤집힘 h60↔h90", "Y_h60 ≠ Y_h90 행", "범위 행", weight="비가중", source=f"{base}.pairwise_svi.h60_vs_h90.svi_flip_rate")
            R.add(f"{p}FlipHundredTwenty", f3(f90120), "SVI 뒤집힘 h90↔h120", "Y_h90 ≠ Y_h120 행", "범위 행", weight="비가중", source=f"{base}.pairwise_svi.h90_vs_h120.svi_flip_rate")
            R.add(f"{p}SameEp", f3(same), "같은 결과 시점 비율 h60↔h90", "e_60 = e_90 행", "범위 행", weight="비가중", source=f"{base}.endpoint_identity.h60_vs_h90.share_same_endpoint")
            fd = "---" if (fdiff is None or fdiff != fdiff) else f3(fdiff)
            R.add(f"{p}FlipDiffEp", fd, "뒤집힘 | 다른 결과 시점 (h60↔h90)", "뒤집힘 행", "e_60 ≠ e_90 행", "같은 프레임 범위는 다른 종점 행이 없어 정의되지 않음(---)", "비가중", f"{base}.endpoint_identity.h60_vs_h90.among_diff_endpoint_svi_flip")
            R.add(f"{p}DbMain", sgn5(tr["delta_brier_q_minus_pt_on_main"]), "ΔBrier q−PT on Y_h90", "Brier(q)−Brier(PT)", "범위 행", "동결 예측", MW, f"{src} `horizon.{c}.frozen_pred_label_transfer.{sc}.Y_h60.delta_brier_q_minus_pt_on_main`")
            R.add(f"{p}DbAlt", sgn5(tr["delta_brier_q_minus_pt_on_alt"]), "ΔBrier q−PT on Y_h60 (라벨 이식)", "Brier(q)−Brier(PT), 라벨만 Y_h60", "범위 행", "동결 예측 고정", MW, f"{src} `...{sc}.Y_h60.delta_brier_q_minus_pt_on_alt`")
            rows.append(f"{SCOPE_KO[sc]} & {fint(st['n'])} & {f3(f6090)} & {f3(f90120)} & {f3(same)} & {f3(fsame)} & {fd} & {sgn5(tr['delta_brier_q_minus_pt_on_main'])} & {sgn5(tr['delta_brier_q_minus_pt_on_alt'])}")
        # h90 vs h120 same-endpoint share (all)
        R.add(f"hz{c}SameEpNinety", f3(H["strata"]["all"]["endpoint_identity"]["h90_vs_h120"]["share_same_endpoint"]), "같은 결과 시점 비율 h90↔h120 (전체)", weight="비가중", source=f"{src} `horizon.{c}.strata.all.endpoint_identity.h90_vs_h120.share_same_endpoint`")
        table(
            f"tab_horizon_strata_{c}.tex",
            f"E4 지평 층화와 h60 라벨 이식 ({c})",
            f"{src} `horizon.{c}`",
            wrap_table(
                f"지평 층화와 h60 라벨 이식 ({'한타 T' if c == 'T' else '소규모 교전 S'}, 15.16 TEST)", f"tab:horizon-strata-{c}",
                "@{}lrrrrrrrr@{}",
                r"범위 & $n$ & 뒤집힘 60$\leftrightarrow$90 & 뒤집힘 90$\leftrightarrow$120 & 같은 종점 60$\leftrightarrow$90 & 뒤집힘$\mid$같은 종점 & 뒤집힘$\mid$다른 종점 & $\Delta$Brier ($Y_{90}$) & $\Delta$Brier ($Y_{60}$)",
                rows,
                "뒤집힘 = 두 지평의 SVI 라벨이 다른 행의 비율(비가중); 같은 종점 = 두 지평의 결과 시점이 같은 행의 비율. "
                "마지막 두 열은 동결 $q$, $\\mathrm{PT}_{\\mathrm{flex}}$ 예측을 고정한 채 라벨만 $Y_{h90}$ 또는 $Y_{h60}$으로 바꿔 계산한 경기 가중 $\\Delta$Brier(구간 없음). 라벨 이식 진단이며 지평을 다시 설계한 결과가 아니다.",
                size=r"\scriptsize",
            ),
        )
    # peer
    P = e4["peer_label_transfer"]
    srcp = f"{src} `peer_label_transfer`"
    R.add("peerName", tex(P["peer"]), "동료 평가기 식별자", source=f"{srcp}.peer")
    R.add("peerN", fint(P["n"]), "행 수 (T TEST)", source=f"{srcp}.n")
    R.add("peerSignAgree", f3(P["sign_agree_nonzero"]), "ΔV 부호 일치율 (주 대 동료 평가기)", "sign 일치 행", f"{fint(P['n_sign_compared'])} 비영 행", weight="비가중", source=f"{srcp}.sign_agree_nonzero")
    R.add("peerFlipAll", f3(P["label_flip_vs_main_all"]), "라벨 뒤집힘 비율 (전체)", "Y_peer ≠ Y_main 행", "행", weight="비가중", source=f"{srcp}.label_flip_vs_main_all")
    prow = []
    for sc in SCOPE_KO:
        b = P["by_scope"][sc]
        p = f"peer{SCOPE_MAC[sc]}"
        R.add(f"{p}N", fint(b["n"]), f"범위 행 수 ({sc})", source=f"{srcp}.by_scope.{sc}.n")
        R.add(f"{p}Flip", f3(b["label_flip_vs_main"]), "라벨 뒤집힘 비율", "Y_peer ≠ Y_main", "범위 행", weight="비가중", source=f"{srcp}.by_scope.{sc}.label_flip_vs_main")
        R.add(f"{p}DbMain", sgn5(b["delta_brier_q_minus_pt_on_main"]), "ΔBrier q−PT on Y_main", cond="동결 예측", weight=MW, source=f"{srcp}.by_scope.{sc}.delta_brier_q_minus_pt_on_main")
        R.add(f"{p}DbAlt", sgn5(b["delta_brier_q_minus_pt_on_alt"]), "ΔBrier q−PT on Y_peer", "예측 고정, 라벨만 동료 평가기", "범위 행", "q 입력의 p_pre는 교체하지 않음", MW, f"{srcp}.by_scope.{sc}.delta_brier_q_minus_pt_on_alt")
        prow.append(f"{SCOPE_KO[sc]} & {fint(b['n'])} & {f3(b['label_flip_vs_main'])} & {sgn5(b['delta_brier_q_minus_pt_on_main'])} & {sgn5(b['delta_brier_q_minus_pt_on_alt'])}")
    table(
        "tab_peer_transfer.tex",
        "E4 동료 평가기 라벨 이식 (T)",
        srcp,
        wrap_table(
            "동료 평가기 라벨 이식 (한타 T, 15.16 TEST)", "tab:peer-transfer",
            "@{}lrrrr@{}", r"범위 & $n$ & 라벨 뒤집힘 & $\Delta$Brier ($Y_{\mathrm{main}}$) & $\Delta$Brier ($Y_{\mathrm{peer}}$)", prow,
            f"동료 평가기 = 같은 입력의 로지스틱 회귀(\\texttt{{{tex(P['peer'])}}}, 기존 선정 이력 있음; TEST에서 새로 고르지 않음). "
            "$Y_{\\mathrm{peer}}$ = 동료 평가기로 같은 예측·결과 시점을 점수화한 SVI. 동결 $q$, $\\mathrm{PT}_{\\mathrm{flex}}$ 예측은 고정, $q$ 입력의 $p_{\\mathrm{pre}}$도 교체하지 않음. 경기 가중, 구간 없음.",
        ),
    )
    # e_fixed
    ef = load("E4F")
    srcf = "`SUPPLEMENTARY_E4_E_FIXED_20260921.json`"
    R.add("efN", fint(ef["n_ok"]), "e_fixed 재구성 성공 행 (T TEST)", source=f"{srcf} `n_ok`")
    R.add("efSameEp", pct1(ef["share_same_endpoint_as_h90"]), "h90과 같은 결과 시점 비율 (%)", "e_fixed = e_90 행", "행", source=f"{srcf} `share_same_endpoint_as_h90`")
    R.add("efFollowFixed", f1(ef["mean_followup_s_fixed"]), "e_fixed 평균 추적 길이 (s)", source=f"{srcf} `mean_followup_s_fixed`")
    R.add("efFollowH", f1(ef["mean_followup_s_h90"]), "h90 평균 추적 길이 (s)", source=f"{srcf} `mean_followup_s_h90`")
    R.add("efFlip", f3(ef["svi_flip_vs_h90"]), "SVI 뒤집힘 e_fixed↔h90", "Y_fixed ≠ Y_h90 행", "행", weight="비가중", source=f"{srcf} `svi_flip_vs_h90`")
    R.add("efDbH", sgn5(ef["frozen_q_pt"]["delta_brier_q_minus_pt_on_Y_h90"]), "ΔBrier q−PT on Y_h90", cond="동결 예측", weight=MW, source=f"{srcf} `frozen_q_pt.delta_brier_q_minus_pt_on_Y_h90`")
    R.add("efDbFixed", sgn5(ef["frozen_q_pt"]["delta_brier_q_minus_pt_on_Y_fixed"]), "ΔBrier q−PT on Y_fixed (라벨 이식)", "예측 고정, 라벨만 e_fixed", "행", weight=MW, source=f"{srcf} `frozen_q_pt.delta_brier_q_minus_pt_on_Y_fixed`")
    # OAT
    oat = load("OAT")
    srco = "`SUPPLEMENTARY_E4_DEFINITION_OAT_20260921.json`"
    R.add("oatNrun", fint(oat["n_matches_run"]), "OAT 실행 경기 수 (hash 선두)", cond="설계 예산 20,000; 검정력 보장 아님", source=f"{srco} `n_matches_run`")
    R.add("oatNdesign", fint(oat["n_matches_design"]), "OAT 설계 경기 수", source=f"{srco} `n_matches_design`")
    # Macro suffixes and display labels for every arm in the extended OAT (G/D/R/B + I/SHOPEX/MR/MD).
    setmac = {
        "ref": "Ref",
        "G_12200": "Gtwelve", "G_15700": "Gfifteen",
        "D_4000": "Dfour", "D_4500": "Dfourfive",
        "R_1400": "Rfourteen", "R_1800": "Reighteen",
        "B_10000": "Bten", "B_20000": "Btwenty",
        "I_2000": "Itwo", "I_2500": "Itwofive", "I_3500": "Ithreefive", "I_4264": "Ifourd",
        "SHOPEX_on": "Shopex",
        "MR_1000": "MRone", "MR_3000": "MRthree",
        "MD_45000": "MDfortyfive", "MD_90000": "MDninety",
    }
    setko = {
        "ref": "기준",
        "G_12200": "$G$ 12.2 s", "G_15700": "$G$ 15.7 s",
        "D_4000": "$D$ 4,000 u", "D_4500": "$D$ 4,500 u",
        "R_1400": "$R$ 1,400 u", "R_1800": "$R$ 1,800 u",
        "B_10000": "$B$ 10 s", "B_20000": "$B$ 20 s",
        "I_2000": "$I$ 2,000 u", "I_2500": "$I$ 2,500 u", "I_3500": "$I$ 3,500 u", "I_4264": "$I{=}D$ 4,264 u",
        "SHOPEX_on": "상점 제외",
        "MR_1000": "병합반경 1,000 u", "MR_3000": "병합반경 3,000 u",
        "MD_45000": "지속상한 45 s", "MD_90000": "지속상한 90 s",
    }
    missing = set(oat["settings"]) - set(setmac)
    if missing:
        raise SystemExit(f"gen_supp OAT: unknown setting keys {sorted(missing)}")
    rows = []
    for s, d in oat["settings"].items():
        p = f"oat{setmac[s]}"
        cc = d["cohort_counts"]
        changed = d.get("changed") or "—"
        R.add(f"{p}Eng", fint(d["n_engagements"]), f"검출 교전 수 ({s})", source=f"{srco} `settings.{s}.n_engagements`")
        R.add(f"{p}T", fint(cc.get("T", 0)), f"T 교전 수 ({s})", cond="n_min ≥ 4", source=f"{srco} `settings.{s}.cohort_counts.T`")
        R.add(f"{p}S", fint(cc.get("S", 0)), f"S 교전 수 ({s})", cond="2 ≤ n_min ≤ 3", source=f"{srco} `settings.{s}.cohort_counts.S`")
        R.add(f"{p}P", fint(cc.get("P", 0)), f"pick 교전 수 ({s})", cond="n_min ≤ 1", source=f"{srco} `settings.{s}.cohort_counts.P`")
        if s == "ref":
            rows.append(
                f"{setko[s]} & --- & {fint(d['n_engagements'])} & {fint(cc.get('T', 0))} & "
                f"{fint(cc.get('S', 0))} & {fint(cc.get('P', 0))} & --- & --- & --- & ---"
            )
        else:
            v = oat["vs_ref"][s]
            moves = v.get("cohort_moves") or {}
            moves_s = ", ".join(f"{k} {fint(n)}" for k, n in sorted(moves.items())) or "---"
            R.add(f"{p}Common", fint(v["n_common_anchors"]), f"기준과 공통 앵커 ({s})", "가장 이른 킬 1:1 일치", source=f"{srco} `vs_ref.{s}.n_common_anchors`")
            R.add(f"{p}RefOnly", fint(v["n_ref_only"]), f"기준에만 있는 교전 ({s})", source=f"{srco} `vs_ref.{s}.n_ref_only`")
            R.add(f"{p}AltOnly", fint(v["n_alt_only"]), f"대안에만 있는 교전 ({s})", source=f"{srco} `vs_ref.{s}.n_alt_only`")
            # Escape underscores in changed labels for LaTeX.
            ch_tex = str(changed).replace("_", r"\_").replace("=", r"$=$")
            rows.append(
                f"{setko[s]} & {ch_tex} & {fint(d['n_engagements'])} & {fint(cc.get('T', 0))} & "
                f"{fint(cc.get('S', 0))} & {fint(cc.get('P', 0))} & {fint(v['n_common_anchors'])} & "
                f"{fint(v['n_ref_only'])} & {fint(v['n_alt_only'])} & {moves_s}"
            )
    table(
        "tab_oat.tex",
        "E4 정의 상수 일변량 변경의 사례 구성 census (확장: I/SHOPEX/MR/MD)",
        f"{srco} `settings`, `vs_ref`",
        wrap_table(
            f"교전 정의 상수의 일변량 변경에 따른 사례 구성 ({fint(oat['n_matches_run'])} 경기)", "tab:oat",
            "@{}l>{\\raggedright\\arraybackslash}p{2.4cm}rrrrrrr>{\\raggedright\\arraybackslash}p{2.8cm}@{}",
            r"설정 & 변경 & 교전 & T & S & pick & 공통 & 기준만 & 대안만 & 계급 이동",
            rows,
            "패치 비율을 유지한 hash 선두 5{,}000 경기(설계 예산 20{,}000; 검정력 보장이 아님). 한 번에 한 상수만 변경. "
            "공통 = 가장 이른 킬이 같은 1:1 대응. 계급 이동은 공통 앵커에서만 집계. "
            "$I$는 상호작용 반경(참여 인원·규모 계급), SHOPEX는 상점 사건 제외, MR/MD는 재교전 병합 반경·지속 상한. "
            "$D$의 대안은 운영적 교란값이며 통계적 구간 경계가 아니다. 고정 $q$/PT 점수는 이 실행에 포함되지 않았다(사례 구성만).",
            size=r"\scriptsize",
        ),
    )


# =============================================================== E5 correspondence / market / R0R1
AXIS_KO = {"kill_diff": "킬 차이", "epic_net": "엘리트 몬스터 순차", "structure_net": "구조물 순차", "objective_net": "오브젝트 순차 (엘리트+구조물)", "alive_diff_post": "종점 생존 차이"}
AXIS_MAC = {"kill_diff": "Kill", "epic_net": "Epic", "structure_net": "Struct", "objective_net": "Obj", "alive_diff_post": "Alive"}


def gen_e5():
    e5 = load("E5")
    src = "`SUPPLEMENTARY_E5_CORRESPONDENCE_20260921.json`"
    rows = []
    for c in ("T", "S"):
        coh = e5["cohorts"][c]
        R.add(f"maN{c}", fint(coh["n"]), f"행 수 ({c})", source=f"{src} `cohorts.{c}.n`")
        for ax in AXIS_KO:
            for sc, scko, scm in (("all_T", "전체", "All"), ("B40", "$B_{40}$", "Bforty")):
                d = coh["material_axes"][ax][sc]
                p = f"ma{c}{AXIS_MAC[ax]}{scm}"
                base = f"{src} `cohorts.{c}.material_axes.{ax}.{sc}`"
                R.add(f"{p}Ndec", fint(d["n_decided"]), "결정 행 수 (축 ≠ 0)", source=f"{base}.n_decided")
                R.add(f"{p}Tie", f3(d["tie_share"]), "동률 비율", "축 = 0 행", "범위 행", source=f"{base}.tie_share")
                R.add(f"{p}Agree", f3(d["agreement_rate_match_weighted_decided"]), "SVI 부호 = 축 부호 일치율", "일치 행", "결정 행", weight=MW, source=f"{base}.agreement_rate_match_weighted_decided")
                R.add(f"{p}Dis", f3(d["disagreement_rate_unweighted_decided"]), "불일치율 (비가중)", "불일치 행", "결정 행", weight="비가중", source=f"{base}.disagreement_rate_unweighted_decided")
                rows.append(f"{c} & {AXIS_KO[ax]} & {scko} & {fint(d['n_decided'])} & {f3(d['tie_share'])} & {f3(d['agreement_rate_match_weighted_decided'])} & {f3(d['disagreement_rate_unweighted_decided'])}")
        kd = coh["kill_disagree_obj"]
        base = f"{src} `cohorts.{c}.kill_disagree_obj`"
        R.add(f"kd{c}N", fint(kd["n_kill_svi_disagree"]), "킬 부호 ≠ SVI 행 수", cond="킬 결정 행 안", source=f"{base}.n_kill_svi_disagree")
        R.add(f"kd{c}Svi", fint(kd["among_disagree_obj_agrees_SVI"]), "그중 오브젝트 순차가 SVI와 일치", source=f"{base}.among_disagree_obj_agrees_SVI")
        R.add(f"kd{c}Kill", fint(kd["among_disagree_obj_agrees_kill"]), "그중 오브젝트 순차가 킬과 일치", source=f"{base}.among_disagree_obj_agrees_kill")
        R.add(f"kd{c}Tie", fint(kd["among_disagree_obj_tie"]), "그중 오브젝트 순차 동률", source=f"{base}.among_disagree_obj_tie")
    table(
        "tab_material_axes.tex",
        "E5 SVI와 물질 결과 축의 동일 사례 대응 (T, S)",
        f"{src} `cohorts.*.material_axes`",
        wrap_table(
            "SVI와 물질적 결과 축의 대응 (15.16 TEST)", "tab:material-axes",
            "@{}lllrrrr@{}", r"코호트 & 축 & 범위 & 결정 $n$ & 동률 비율 & 일치율 & 불일치율", rows,
            "축 = 결과 시점(h90) 상태에서 계산한 블루$-$레드 순차(킬·엘리트 몬스터·구조물·둘의 합·생존 인원). 결정 = 축이 0이 아닌 행; 일치율 = 결정 행 가운데 SVI 부호와 축 부호가 같은 비율(경기 가중); 불일치율은 비가중. "
            "물질 특징은 $\\hat V$의 입력과 겹치므로 같은 사례 안의 대응이다.",
            size=r"\footnotesize",
        ),
    )
    # nextobj (T)
    nx = e5["cohorts"]["T"]["nextobj"]
    srcn = f"{src} `cohorts.T.nextobj`"
    rows = []
    for sc, scko, scm in (("all_T", "전체", "All"), ("B40", "$B_{40}$", "Bforty"), ("SVI_pos", "SVI $=1$", "Pos"), ("SVI_neg", "SVI $=0$", "Neg")):
        d = nx[sc]
        p = f"no{scm}"
        R.add(f"{p}N", fint(d["n"]), f"범위 행 수 ({sc})", source=f"{srcn}.{sc}.n")
        R.add(f"{p}NBR", fint(d["n_decided_BlueRed"]), "180 s 안 첫 엘리트 오브젝트가 Blue 또는 Red인 행", cond="none/경기 종료/동률 제외", source=f"{srcn}.{sc}.n_decided_BlueRed")
        R.add(f"{p}SviAgree", f3(d["SVI_agree_rate"]), "P(Y_SVI = 1[O = Blue] | O ∈ {Blue, Red})", "SVI 방향과 획득 팀이 일치한 행", "Blue|Red 행", "선택된 분모", "비가중", f"{srcn}.{sc}.SVI_agree_rate")
        R.add(f"{p}NKill", fint(d["n_kill_decided_in_selected"]), "Blue|Red 행 중 킬 차이 ≠ 0인 행", source=f"{srcn}.{sc}.n_kill_decided_in_selected")
        R.add(f"{p}KillAgree", f3(d["kill_agree_rate_among_kill_decided"]), "P(sign(kill) = 1[O = Blue] | Blue|Red, kill ≠ 0)", "킬 부호와 획득 팀 일치 행", "Blue|Red ∩ 킬 결정 행", "SVI 일치율과 분모가 다름", "비가중", f"{srcn}.{sc}.kill_agree_rate_among_kill_decided")
        R.add(f"{p}BlueShare", f3(d["SVI_Blue_rate_among_selected"]), "Blue|Red 행 중 SVI = 1 비율", source=f"{srcn}.{sc}.SVI_Blue_rate_among_selected")
        cnt = d["counts"]
        rows.append(f"{scko} & {fint(d['n'])} & {fint(cnt['Blue'])} & {fint(cnt['Red'])} & {fint(d['n_decided_BlueRed'])} & {f3(d['SVI_agree_rate'])} & {fint(d['n_kill_decided_in_selected'])} & {f3(d['kill_agree_rate_among_kill_decided'])}")
    table(
        "tab_nextobj.tex",
        "E5 다음 엘리트 오브젝트와의 연관 (T)",
        srcn,
        wrap_table(
            "다음 엘리트 오브젝트와의 연관 (한타 T, 15.16 TEST)", "tab:nextobj",
            "@{}lrrrrrrr@{}", r"범위 & $n$ & Blue & Red & Blue$|$Red & SVI 일치율 & 킬 결정 & 킬 일치율", rows,
            "$O$ = 결과 시점 뒤 180 s 안의 첫 엘리트 오브젝트 획득 팀(RR5b 라벨 재사용). Blue$|$Red = $O\\in\\{\\mathrm{Blue},\\mathrm{Red}\\}$인 행(없음·경기 종료·동률 제외). "
            "SVI 일치율 = $P(Y_{\\mathrm{SVI}} = \\mathbf 1[O=\\mathrm{Blue}] \\mid \\mathrm{Blue}|\\mathrm{Red})$; 킬 일치율 = 같은 조건에 킬 차이 $\\ne 0$을 더한 분모에서 킬 부호와 $O$의 일치율. 두 일치율은 분모가 다르다. 비가중, 구간 없음.",
            size=r"\footnotesize",
        ),
    )
    # market_event / R0R1
    m = load("E5M")
    srcm = "`SUPPLEMENTARY_E5_MARKET_R0R1_20260921.json`"
    me = m["market_event"]
    R.add("meN", fint(me["n_ok"]), "market_event 계산 성공 행 (T TEST)", source=f"{srcm} `market_event.n_ok`")
    R.add("meFlip", f3(me["label_flip_vs_SVI"]), "교환가치 라벨 ≠ SVI 비율", "부호가 다른 행", "행", "같은 (s, e_90+1 ms) 창; v3.3 market_event", "비가중", f"{srcm} `market_event.label_flip_vs_SVI`")
    R.add("meAgree", f3(me["agree_rate"]), "교환가치 라벨 = SVI 비율", weight="비가중", source=f"{srcm} `market_event.agree_rate`")
    R.add("meDbSvi", sgn5(me["delta_brier_q_minus_pt_on_SVI"]), "ΔBrier q−PT on SVI", cond="동결 예측", weight=MW, source=f"{srcm} `market_event.delta_brier_q_minus_pt_on_SVI`")
    R.add("meDbMarket", sgn5(me["delta_brier_q_minus_pt_on_market"]), "ΔBrier q−PT on 교환가치 라벨 (라벨 이식)", "예측 고정, 라벨만 market_event", "행", weight=MW, source=f"{srcm} `market_event.delta_brier_q_minus_pt_on_market`")
    r = m["r0_r1"]
    R.add("rTrainN", fint(r["train_n"]), "R 모형 TRAIN 행 (T, OOF ΔV)", source=f"{srcm} `r0_r1.train_n`")
    R.add("rQcalN", fint(r["qcal_n"]), "R 모형 Q_CAL 행", source=f"{srcm} `r0_r1.qcal_n`")
    R.add("rQselN", fint(r["qsel_n"]), "R 모형 Q_SELECT 행", source=f"{srcm} `r0_r1.qsel_n`")
    R.add("rTestN", fint(r["test_n"]), "R 모형 TEST 행", source=f"{srcm} `r0_r1.test_n`")
    R.add("rZeroBrier", f4(r["R0"]["brier_TEST"]), "R0 TEST 다항 Brier (클래스 합)", "Σ_k (p_k − 1[U=k])²", "TEST 행", "U = 180 s 안 첫 엘리트 오브젝트 결과 (6 클래스)", MW, f"{srcm} `r0_r1.R0.brier_TEST`")
    R.add("rOneBrier", f4(r["R1"]["brier_TEST"]), "R1 TEST 다항 Brier", cond="R1 = R0 + ΔV̂", weight=MW, source=f"{srcm} `r0_r1.R1.brier_TEST`")
    R.add("rDelta", sgn5(r["delta_brier_R1_minus_R0_TEST"]), "R1 − R0 다항 Brier 차", cond="구간 없음", weight=MW, source=f"{srcm} `r0_r1.delta_brier_R1_minus_R0_TEST`")
    R.add("rZeroBR", f4(r["R0"]["brier_TEST_BlueRed_selected"]), "R0 Brier, Blue|Red 선택 분모", cond="선택된 분모", source=f"{srcm} `r0_r1.R0.brier_TEST_BlueRed_selected`")
    R.add("rOneBR", f4(r["R1"]["brier_TEST_BlueRed_selected"]), "R1 Brier, Blue|Red 선택 분모", cond="선택된 분모", source=f"{srcm} `r0_r1.R1.brier_TEST_BlueRed_selected`")
    R.add("rC", f"{r['R0']['C']:g}", "R0/R1 L2 규제 C (Q_SELECT 선정)", source=f"{srcm} `r0_r1.R0.C`")


# =============================================================== G0
def gen_g0():
    g = load("G0")
    src = "`G0_INTEGRITY_STATUS_20260921.json`"
    R.add("gzOverall", tex(g["overall_status"]), "G0 전체 상태", source=f"{src} `overall_status`")
    keymap = {
        "G0.1_provenance_record": "One", "G0.2_evaluator_hash_after_finalize": "Two", "G0.3_s_reuse_and_write_guard": "Three",
        "G0.4_join_key_integrity": "Four", "G0.5_fold_holdout_match_set": "Five", "G0.6_bundle_reload_parity": "Six",
        "G0.7_headline_reaggregate": "Seven", "G0.8_missing_data_policy": "Eight", "G0.F_future_info_invariance": "Future",
        "unit_tests_provenance": "Unit",
    }
    for k, mac in keymap.items():
        R.add(f"gzStatus{mac}", tex(g["checks"][k]["status"]), f"검사 {k} 상태", source=f"{src} `checks.{k}.status`")
    pb = g["phase_b"]
    R.add("gzDigestN", fint(pb["digests"]["n_match"]), "digest MATCH 아티팩트 수", source=f"{src} `phase_b.digests.n_match`")
    R.add("gzDigestDiff", fint(pb["digests"]["n_diff"]), "digest 불일치 수", source=f"{src} `phase_b.digests.n_diff`")
    for c, mac in (("T", "T"), ("S_identity", "S")):
        h = pb["headlines"]["cohorts"][c]
        R.add(f"gzReagg{mac}", f8(h["delta_brier_q_minus_PT_flex"]), f"동결 예측표 재집계 ΔBrier ({c})", "Brier(q)−Brier(PT_flex)", f"{fint(h['n_rows'])} 행 / {fint(h['n_matches'])} 경기", weight=MW, source=f"{src} `phase_b.headlines.cohorts.{c}.delta_brier_q_minus_PT_flex`")
        R.add(f"gzPrint{mac}", f"{h['docs_delta_printed']:+.5f}", f"문서 인쇄값 ({c})", source=f"{src} `...docs_delta_printed`")
    R.add("gzFoldN", str(len(pb["oof_reload"]["folds"])), "재적재한 OOF 평가기 수", source=f"{src} `phase_b.oof_reload.folds`")
    R.add("gzOofStatus", tex(pb["oof_reload"]["status"]), "OOF 재적재 상태", source=f"{src} `phase_b.oof_reload.status`")


# =============================================================== main
def generate(outroot: Path):
    gen_e1()
    gen_e2()
    gen_e3()
    gen_e4()
    gen_e5()
    gen_g0()
    latex = outroot / "thesis" / "latex"
    (latex / "config").mkdir(parents=True, exist_ok=True)
    (latex / "tables" / "gen").mkdir(parents=True, exist_ok=True)
    (outroot / "thesis" / "docs").mkdir(parents=True, exist_ok=True)
    written = {}
    written[latex / "config" / "numbers_supp.tex"] = R.tex()
    for fn, body in TABLES.items():
        written[latex / "tables" / "gen" / fn] = body
    written[outroot / "thesis" / "docs" / "NUMBERS_SUPP.md"] = R.md(TABLE_DESC)
    for p, s in written.items():
        p.parent.mkdir(parents=True, exist_ok=True)
        p.write_text(s, encoding="utf-8")
    return written


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", default=str(ROOT), help="output root (default: repo root)")
    a = ap.parse_args()
    w = generate(Path(a.out))
    print(f"wrote {len(w)} files; {len(R.rows)} macros; {len(TABLES)} tables")
