#!/usr/bin/env python3
"""Generate thesis/latex/tables/gen/tab_status.tex from thesis/docs/STATUS.md (sections 2 and 3),
so the appendix status table cannot drift from the evidence ledger. Also usable as a check
(--check): exit 1 if the committed table differs from a fresh render."""
from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
STATUS = ROOT / "thesis" / "docs" / "STATUS.md"
OUT = ROOT / "thesis" / "latex" / "tables" / "gen" / "tab_status.tex"

STATUS_KO = {
    "FROZEN": "동결",
    "DONE": "실행",
    "PASS": "통과",
    "PARTIAL": "부분",
    "INCOMPLETE": "미완료",
    "NOT_RUN": "미실행",
    "BLOCKED": "차단",
    "DEFERRED": "이연",
}


def tex(s: str) -> str:
    s = s.replace("\\", "")
    s = re.sub(r"`([^`]*)`", lambda m: "\\path{" + m.group(1) + "}", s)
    for a, b in (("&", r"\&"), ("%", r"\%"), ("#", r"\#"), ("_", r"\_"), ("×", r"$\times$"), ("≥", r"$\ge$"), ("≤", r"$\le$"), ("−", "$-$"), ("→", r"$\to$")):
        s = s.replace(a, b)
    # \path{} content must not carry escaped underscores
    s = re.sub(r"\\path\{([^}]*)\}", lambda m: "\\path{" + m.group(1).replace(r"\_", "_").replace(r"\#", "#") + "}", s)
    return s


def parse_sections(text: str):
    """Return list of (section_title, rows) for sections 2 and 3; rows = list of dicts."""
    out = []
    cur = None
    for line in text.splitlines():
        m = re.match(r"^## (\d)\. (.*)", line)
        if m:
            cur = None
            if m.group(1) in ("2", "3"):
                cur = (m.group(2).strip(), [])
                out.append(cur)
            continue
        if cur is None or not line.startswith("|"):
            continue
        cells = [c.strip() for c in line.strip().strip("|").split("|")]
        if cells[0] in ("ID", "") or set(cells[0]) <= {"-"}:
            continue
        cur[1].append(cells)
    return out


def render(sections) -> str:
    lines = [
        "%% GENERATED by thesis/tools/gen_status_table.py from thesis/docs/STATUS.md -- do not edit",
        r"\begin{longtable}{@{}p{4.4cm}p{6.2cm}lp{2.6cm}@{}}",
        r"  \caption{보완 분석과 이연 항목의 실행 상태}\label{tab:status}\\",
        r"  \toprule",
        r"  ID & 하위 분석 & 상태 & 본문 \\",
        r"  \midrule",
        r"  \endfirsthead",
        r"  \toprule",
        r"  ID & 하위 분석 & 상태 & 본문 \\",
        r"  \midrule",
        r"  \endhead",
        r"  \bottomrule",
        r"  \endfoot",
    ]
    for title, rows in sections:
        lines.append(f"  \\multicolumn{{4}}{{@{{}}l}}{{\\emph{{{tex(title)}}}}} \\\\")
        for cells in rows:
            sid = cells[0]
            desc = cells[1]
            status = cells[2]
            loc = cells[4] if len(cells) > 4 else (cells[3] if len(cells) > 3 else "")
            ko = STATUS_KO.get(status, status)
            lines.append(f"  \\path{{{sid}}} & {tex(desc)} & {ko} (\\texttt{{{tex(status)}}}) & {tex(loc)} \\\\")
    lines += [r"\end{longtable}", ""]
    return "\n".join(lines)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    a = ap.parse_args()
    sections = parse_sections(STATUS.read_text(encoding="utf-8"))
    body = render(sections)
    if a.check:
        if not OUT.exists() or OUT.read_text(encoding="utf-8") != body:
            print(f"DRIFT    {OUT.relative_to(ROOT)}  (re-run thesis/tools/gen_status_table.py)")
            return 1
        print("status table: OK")
        return 0
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(body, encoding="utf-8")
    n = sum(len(r) for _, r in sections)
    print(f"wrote {OUT.relative_to(ROOT)} ({n} rows)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
